### ISSUE TITLE
Incorrect train displayed on overnight trains

### ISSUE THREAD

**Issue by ian13** [poggs/tsdbexplorer#80] opened 2012-02-07 19:15 UTC
Where trains run overnight, the incorrect date is used following midnight.

To reproduce:
http://www.opentraintimes.com/location/BRI/2012/2/13/0033
links to 2C97 running on  Monday13th terminating Tuesday 14th

2C97 doesn't run on Sunday 12th, and thus shouldn't be shown as arriving at 0033 on Monday 13th.

**Comment by poggs** [comment] 2012-02-07 19:33
Duplicate of issue #8

**Comment by ian13** [comment] 2012-02-08 23:09
Whilst #8 is related, this issue exists where the time-range requested is entirely within the following day.

The 'to reproduce' issue remains on current version.

**Comment by poggs** [comment] 2012-02-08 23:30
Issue confirmed

**Comment by ian13** [comment] 2012-02-08 23:44
The best example I can think of is the sleeper. The Scotrail sleeper doesn't run Saturday night (arriving Sunday morning). Yet, look for a 747 arrival at Euston from Inverness. If you click it you'll see it's actually the Sunday timetable (for arrival into Euston on Monday).

-> Can you provide an example?  I'm still having trouble reproducing this

**Comment by poggs** [comment] 2012-02-10 08:07
Fixed in poggs/tsdbexplorer@e530ef606f2b622c0add172e0cddaa2d0e3968e1

**Comment by ian13** [comment] 2012-02-10 23:12
This commit does not appear to have fully solved the problem.

In the handling of overnight trains for all stops reached after midnight:
- The train will have started the previous day, and it is this schedule that must be used/linked to
- The train that started that day (where applicable) won't be there until the following day

The original example remains an issue:
http://www.opentraintimes.com/location/BRI/2012/2/13/0033

This link shows the early-morning arrivals on Monday 13th. The 0033 arrival linked to is the "2327 Cardiff Central to Bristol Temple Meads" departing on Monday the 13th, but not arriving into Bristol Temple Meads until Tuesday 14th. There isn't actually a 2327 arrival at Bristol Temple Meads on a Monday morning, as the service doesn't run on Sundays.

**Comment by poggs** [comment] 2012-02-10 23:53
OK, I see what's happened, I've inadvertently fixed a completely separate, similar bug in the same code.

**Comment by poggs** [comment] 2012-02-11 00:37
Can you try replacing the runs_on scope in app/models/location.rb with the following and confirm whether this fixes the bug?  I won't check this code in just yet, it breaks some other specs which appear to be incorrect and require me to rework them.

  scope :runs_on, lambda { |date| joins('JOIN basic_schedules ON locations.basic_schedule_uuid = basic_schedules.uuid').where('? BETWEEN basic_schedules.runs_from AND basic_schedules.runs_to', date).where([ 'basic_schedules.runs_su', 'basic_schedules.runs_mo', 'basic_schedules.runs_tu', 'basic_schedules.runs_we', 'basic_schedules.runs_th', 'basic_schedules.runs_fr', 'basic_schedules.runs_sa' ][Date.parse(date).wday] => true ).where('stp_indicator IN (SELECT MIN(stp_indicator) FROM basic_schedules AS bs2 WHERE train_uid = basic_schedules.train_uid AND ? BETWEEN runs_from AND runs_to)', date).where('(SELECT departure FROM locations WHERE activity_tb = true AND locations.basic_schedule_uuid = basic_schedules.uuid) < (SELECT arrival FROM locations WHERE activity_tf = true AND locations.basic_schedule_uuid = basic_schedules.uuid)') }

**Comment by ian13** [comment] 2012-02-11 14:01
Well, that seems to stop my  "2327 Cardiff Central to Bristol Temple Meads" example from showing up on a Monday night - but it doesn't seem to show up on a Tuesday night either.  It seems that no overnight trains display after midnight. (Development env.)

**Comment by poggs** [comment] 2012-02-11 23:59
OK, we'll get there eventually.  I'll have another crack at it tomorrow.

**Comment by poggs** [comment] 2012-02-17 07:05
Update: I've found the bug!  The fix isn't straightforward as it requires a database schema change to identify calls after midnight, and I'm working on fixing a couple of edge-cases that currently fail.

**Comment by poggs** [comment] 2012-03-06 22:45
Confirmed fixed

**Closed as completed by poggs** 2012-03-06 22:45 UTC
Labels: backend, bug
